Spring:
   jpa:
     defer-datasource-initialization: false
     hibernate:
       ddl-auto: none
     show-sql: true
     properties:
       hibernate:
         format_sql: true
     open-in-view: false
   flyway:
     default-schema: public
     baseline-on-migrate: true
   datasource:
     url: jdbc:postgresql://localhost:5432/hotel_db
     username: postgres
     password: postgres

server:
  port: 8080